#!/bin/lsbuild.sh -nodeps
SRCLINK=https://downloads.uclibc-ng.org/releases/{{version}}/{{pkgname}}-{{version}}.tar.xz
HOMEPAGE=https://uclibc-ng.org
DESCRIPTION="small C library for developing embedded Linux systems"
STRIPMODE=none
DEVPKG=true

BUILD_DEPENDS="kernel-headers"

doconf defconfig \
  set KERNEL_HEADERS=/usr/include RUNTIME_PREFIX=/ DEVEL_PREFIX=/usr MULTILIB_DIR=lib \
  unset DOASSERTS DODEBUG_PT HAS_NO_THREADS PROPOLICE_BLOCK_ABRT SSP_QUICK_CANARY \
        SUPPORT_LD_DEBUG_EARLY UCLIBC_HAS_CTYPE_UNSAFE UCLIBC_HAS_LOCALE LDSO_SAFE_RUNPATH \
  set DO_C99_MATH DO_XSI_MATH FORCE_SHAREABLE_TEXT_SEGMENTS LDSO_GNU_HASH_SUPPORT \
      LDSO_PRELOAD_FILE_SUPPORT LDSO_RUNPATH LDSO_RUNPATH_OF_EXECUTABLE LDSO_STANDALONE_SUPPORT \
      PROPOLICE_BLOCK_SEGV PTHREADS_DEBUG_SUPPORT UCLIBC_HAS_ARC4RANDOM UCLIBC_HAS_BACKTRACE \
      UCLIBC_HAS_BSD_RES_CLOSE UCLIBC_HAS_CONTEXT_FUNCS UCLIBC_HAS_CTYPE_CHECKED \
      UCLIBC_HAS_EXTRA_COMPAT_RES_STATE UCLIBC_HAS_FENV UCLIBC_HAS_FOPEN_CLOSEEXEC_MODE \
      UCLIBC_HAS_FOPEN_EXCLUSIVE_MODE UCLIBC_HAS_FOPEN_LARGEFILE_MODE UCLIBC_HAS_FTS \
      UCLIBC_HAS_FTW UCLIBC_HAS_GETPT UCLIBC_HAS_GLIBC_CUSTOM_PRINTF UCLIBC_HAS_GLIBC_CUSTOM_STREAMS \
      UCLIBC_HAS_GNU_GLOB UCLIBC_HAS_HEXADECIMAL_FLOATS UCLIBC_HAS_LIBUTIL UCLIBC_HAS_NFTW \
      UCLIBC_HAS_OBSOLETE_BSD_SIGNAL UCLIBC_HAS_PRINTF_M_SPEC UCLIBC_HAS_PROGRAM_INVOCATION_NAME \
      UCLIBC_HAS_RESOLVER_SUPPORT UCLIBC_HAS_SHA256_CRYPT_IMPL UCLIBC_HAS_SHA512_CRYPT_IMPL \
      UCLIBC_HAS_SSP UCLIBC_HAS_STUBS UCLIBC_HAS_SYS_ERRLIST UCLIBC_HAS_SYS_SIGLIST \
      UCLIBC_HAS_THREADS_NATIVE UCLIBC_HAS_TZ_FILE_READ_MANY UCLIBC_HAS_UTMP UCLIBC_HAS_UTMPX \
      UCLIBC_HAS_WCHAR UCLIBC_HAS_WORDEXP UCLIBC_NTP_LEGACY UCLIBC_SUPPORT_AI_ADDRCONFIG \
      UCLIBC_SUSV2_LEGACY UCLIBC_SUSV3_LEGACY UCLIBC_SUSV3_LEGACY_MACROS UCLIBC_SUSV4_LEGACY \
      UCLIBC_USE_NETLINK
dobuild
doinstall
